MODFEE-328 Add the field "effectiveLocationDiscoveryDisplayName" to the Item Object in the Notice context
folio-org/mod-feesfines pull request #272
Opened 2023-03-24 07:48 UTC by pavankumar181

**Purpose**
This PR serves the purpose to add the value of Item.effectiveLocationDiscoveryDisplayName in the Notice Context which is required as per [https://issues.folio.org/browse/MODFEE-328](url) for Manual fee/fine charge + Manual fee/fine action (pay, waive, refund, transfer or cancel/error).
**Approach**
We already have the field discoveryDisplayName in Location Object so at the time of preparing Notice context
we are adding the above value and set it to the Item Context.
After this change, LocationDiscoveryDisplayName is populated in the Notices. Please find the Email Evidence below
![MODFEE-328-2](https://user-images.githubusercontent.com/127184919/227457372-6e049694-343b-4163-83bf-195086f902e8.JPG)
![MODFEE-328-1](https://user-images.githubusercontent.com/127184919/227457375-0cfefe92-c42d-452b-8b23-6726d80863f4.JPG)

2023-03-24 07:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/mod-feesfines?pullRequest=272) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/mod-feesfines?pullRequest=272) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/mod-feesfines?pullRequest=272) it.</sub>

2023-03-24 08:50 UTC, gurleenkaurbp requested changes

2023-03-24 08:50 UTC, gurleenkaurbp commented on src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
Please create a constant for effectiveLocationDiscoveryDisplayName like EFFECTIVE_LOCATION_SPECIFIC

2023-03-28 10:19 UTC, OleksandrVidinieiev approved these changes

2023-03-29 06:44 UTC, pavankumar181 commented on src/main/java/org/folio/rest/utils/PatronNoticeBuilder.java
completed

2023-03-29 06:45 UTC, Vignesh-kalyanasundaram approved these changes

2023-03-29 08:57 UTC, gurleenkaurbp approved these changes

2023-03-29 11:53 UTC, merged